version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.9.0

jobs: 
  build:
    docker: 
    - image: cimg/base:2023.06
    steps:
    - name: Set dataset name
    - run: |
        export BUILDEVENT_DATASET=alex-demo
    - buildevents/start_trace
    - checkout
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
    - run: 
        name: Building Image
        command: docker build . -t $CONTAINER_NAME:CIRCLE_TAG
        environment:
          CONTAINER_NAME: sample-app 
          BUILDEVENT_DATASET: alex-demo
    - buildevents/create_marker:
        dataset: alex-demo
        message: this is a demo $CIRCLE_BUILD_NUM

  watch:
    docker: 
    - image: cimg/base:2023.06
    steps:
    - buildevents/watch_build_and_finish

workflows:
  img_docker:
    jobs:
      - build
      - watch:
          requires:
            - build