version: 2.1

executors:
  docker:
    docker:
      - image: cimg/base:2023.06
    resource_class: medium
    environment:
          IMAGE_NAME: registry.gitlab.com/and-amavrogiannis/lab-project/sample-app

jobs:

  setup: 
    executor: 
      name: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
    

  build:
    executor: 
      name: docker
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker build -t "${IMAGE_NAME}:${CIRCLE_SHA1}" .
  
  deploy:
    executor: 
      name: docker
    steps:
      - run: 
          name: Docker push
          command: |
            docker login --username $GL_USER --password $REG_TOKEN registry.gitlab.com
            docker push "${IMAGE_NAME}:${CIRCLE_SHA1}"

workflows:

  docker_image:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - deploy: 
          requires:
            - build 