version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.9.0

jobs: 

  setup: 
    docker: 
    - image: cimg/base:2023.06
    steps:
    - buildevents/start_trace
    environment:
      BUILDEVENT_DATASET: alex-demo

  # watch:
  #   docker: 
  #   - image: cimg/base:2023.06
  #   steps:
  #   - buildevents/finish

  build: 
    docker:
      - image: cimg/base:2023.06
    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            - setup_remote_docker:
                version: 20.10.14
                docker_layer_caching: true
            - run: 
                name: build_img
                command: |
                  docker build . -t $CONTAINER_NAME:$CIRCLE_SHA1
                environment:
                  CONTAINER_NAME: sample-app
      - buildevents/add_context:
          field_name: demo_data
          field_value: $CONTAINER_NAME:$CIRCLE_SHA1
          verbose: true


workflows:
  img_docker:
    jobs:
      - setup
      - build:
          requires:
            - setup
      # - watch:
      #     requires:
      #       - setup