version: 2.1

jobs:

  setup: 
    docker: 
      - image: cimg/base:2023.06
    resource_class: medium
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
    environment:
      CONTAINER_NAME: lab-project/sample-app

  build:
    docker: 
      - image: cimg/base:2023.06
    steps:
      - run:
          command: |  
            docker build . -t $CONTAINER_NAME:$CIRCLE_SHA1
  
  deploy:
    docker: 
      - image: cimg/base:2023.06
    steps:
      - run: 
          name: Docker push
          command: |
            docker login --username $GL_USER --password $REG_TOKEN registry.gitlab.com

workflows:

  docker_image:
    jobs:
      - setup
      - build: 
          requires:
            - setup
      - deploy: 
          requires:
            - build 