version: 2.1

executors:
  docker:
    docker:
      - image: cimg/base:2023.06
    resource_class: medium
    environment:
          IMAGE_NAME: registry.gitlab.com/and-amavrogiannis/lab-project/sample-app

jobs:

  build:
    executor: 
      name: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - checkout
      - run:
          name: Docker build
          command: docker build -t "${IMAGE_NAME}:${CIRCLE_SHA1}" .
      - run: 
          name: Save image
          command: |
            mkdir -p image_artifact
            docker image save -o "image_artifact/ZIP_${CIRCLE_SHA1}" "${IMAGE_NAME}:${CIRCLE_SHA1}"
      - persist_to_workspace:
          root: .
          paths:
            - image_artifact
  
  deploy:
    executor: 
      name: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - attach_workspace:
          at: .
      - run: 
          name: Load Image
          command: |
            docker image load < "image_artifact/ZIP_${CIRCLE_SHA1}"
      - run: 
          name: Docker push
          command: |
            docker login --username $GL_USER --password $REG_TOKEN registry.gitlab.com
            docker push "${IMAGE_NAME}:${CIRCLE_SHA1}"

workflows:

  docker_image:
    jobs:
      - build
      - deploy: 
          requires:
            - build 